// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.Data;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260215172351_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Repositories.Entities.MonthIdToMonthName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("MonthId")
                        .HasColumnType("tinyint");

                    b.Property<string>("MonthName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__MonthIdT__3214EC0772F4F23C");

                    b.HasIndex(new[] { "MonthId" }, "UX_MonthIdToMonthName_MonthId")
                        .IsUnique();

                    b.ToTable("MonthIdToMonthName", null, t =>
                        {
                            t.HasTrigger("trg_MonthIdToMonthName_BlockAllDML");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Repositories.Entities.Observation", b =>
                {
                    b.Property<int>("ObservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObservationId"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())", "DF_Observation_CreatedDate");

                    b.Property<int>("ObservationMonthId")
                        .HasColumnType("int");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.HasKey("ObservationId")
                        .HasName("PK__Observat__420EA5E7B5D44F9F");

                    b.HasIndex("SpeciesId");

                    b.HasIndex(new[] { "ObservationMonthId", "SpeciesId" }, "UQ_Observation")
                        .IsUnique();

                    b.ToTable("Observation");
                });

            modelBuilder.Entity("Repositories.Entities.ObservationMonth", b =>
                {
                    b.Property<int>("ObservationMonthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObservationMonthId"));

                    b.Property<int>("ObservationMonth1")
                        .HasColumnType("int")
                        .HasColumnName("ObservationMonth");

                    b.Property<int>("ObservationYear")
                        .HasColumnType("int");

                    b.HasKey("ObservationMonthId")
                        .HasName("PK__Observat__3516F905F247AB49");

                    b.HasIndex(new[] { "ObservationYear", "ObservationMonth1" }, "UQ_ObservationMonth")
                        .IsUnique();

                    b.ToTable("ObservationMonth");
                });

            modelBuilder.Entity("Repositories.Entities.Species", b =>
                {
                    b.Property<int>("SpeciesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpeciesId"));

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SpeciesName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SpeciesId")
                        .HasName("PK__Species__A938045F9B499056");

                    b.HasIndex(new[] { "SpeciesName" }, "UQ__Species__304D4C0D31EE26C3")
                        .IsUnique();

                    b.ToTable("Species");
                });

            modelBuilder.Entity("Repositories.Entities.Vw_top_list_per_month", b =>
                {
                    b.Property<string>("MonthName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ObservationYear")
                        .HasColumnType("int");

                    b.Property<int?>("antal")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("Vw_top_list_per_month", (string)null);
                });

            modelBuilder.Entity("Repositories.Entities.Vw_top_list_per_specy", b =>
                {
                    b.Property<int?>("ObservationCount")
                        .HasColumnType("int");

                    b.Property<string>("SpeciesName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable((string)null);

                    b.ToView("Vw_top_list_per_species", (string)null);
                });

            modelBuilder.Entity("Repositories.Entities.Vw_total_list", b =>
                {
                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MonthName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("Månadsnummer")
                        .HasColumnType("tinyint");

                    b.Property<int>("ObservationYear")
                        .HasColumnType("int");

                    b.Property<string>("SpeciesName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable((string)null);

                    b.ToView("Vw_total_list", (string)null);
                });

            modelBuilder.Entity("Repositories.Entities.Observation", b =>
                {
                    b.HasOne("Repositories.Entities.ObservationMonth", "ObservationMonth")
                        .WithMany("Observations")
                        .HasForeignKey("ObservationMonthId")
                        .IsRequired()
                        .HasConstraintName("FK_Observation_Month");

                    b.HasOne("Repositories.Entities.Species", "Species")
                        .WithMany("Observations")
                        .HasForeignKey("SpeciesId")
                        .IsRequired()
                        .HasConstraintName("FK_Observation_Species");

                    b.Navigation("ObservationMonth");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Repositories.Entities.ObservationMonth", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("Repositories.Entities.Species", b =>
                {
                    b.Navigation("Observations");
                });
#pragma warning restore 612, 618
        }
    }
}
